apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: proxy
  name: wavefront-proxy
spec:
  ports:
  - name: wavefront
    port: 2878
    protocol: TCP
  selector:
    app.kubernetes.io/component: proxy
  type: ClusterIP